name: 'dbt_anomaly_detection'
version: '0.1.0'
config-version: 2

# Require dbt version 1.3.0 or higher (but below 2.0.0)
require-dbt-version: [">=1.3.0", "<2.0.0"]

# SNOWFLAKE ONLY: This package uses Snowflake-specific features
# (information_schema, generator(), date functions)

profile: 'default'

# This setting configures which "profile" dbt uses for this project.
# For package consumers, this will use their own profile configuration.

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Package configuration
vars:
  # Volume anomaly detection settings
  volume_anomaly_detection:
    # Default lookback period for anomaly detection (days)
    lookback_days: 28
    # Default minimum historical observations required
    min_historical_observations: 7

    # # Row Count CHANGE sensitivity (growth rate detection - more volatile)
    # # Calibrated from wide (quiet) to narrow (noisy) tolerance
    # row_count_change_sensitivity_very_low: 32.0   # 32σ threshold - extremely wide, only catastrophic issues (RECOMMENDED DEFAULT)
    # row_count_change_sensitivity_low: 16.0        # 16σ threshold - catches significant growth changes
    # row_count_change_sensitivity_medium: 8.0      # 8σ threshold - balanced middle ground
    # row_count_change_sensitivity_high: 6.0        # 6σ threshold - catches smaller deviations
    # row_count_change_sensitivity_very_high: 4.0   # 4σ threshold - narrow, very noisy

    # # Absolute ROW COUNT sensitivity (total size detection - more stable)
    # # Calibrated from wide (quiet) to narrow (noisy) tolerance
    # row_count_sensitivity_very_low: 6.0     # 6σ threshold - very wide, only major issues (RECOMMENDED DEFAULT)
    # row_count_sensitivity_low: 4.0          # 4σ threshold - catches significant size changes
    # row_count_sensitivity_medium: 3.0       # 3σ threshold - balanced middle ground
    # row_count_sensitivity_high: 2.0         # 2σ threshold - catches smaller deviations
    # row_count_sensitivity_very_high: 1.0    # 1σ threshold - narrow, very noisy

    # Enable/disable volume monitoring globally
    enabled: true

  # Freshness anomaly detection settings
  freshness_anomaly_detection:
    # Default lookback period for anomaly detection (days)
    lookback_days: 28
    # Default minimum historical observations required
    min_historical_observations: 7
    # Sensitivity thresholds (sigma/standard deviations from mean)
    # Calibrated from wide (quiet) to narrow (noisy) tolerance
    sensitivity_very_low: 2.0    # 2σ threshold - wide, rare alerts (RECOMMENDED DEFAULT)
    sensitivity_low: 1.5         # 1.5σ threshold - catches significant staleness
    sensitivity_medium: 1.0      # 1σ threshold - balanced middle ground
    sensitivity_high: 0.75       # 0.75σ threshold - catches smaller staleness
    sensitivity_very_high: 0.5   # 0.5σ threshold - narrow, very noisy
    # Enable/disable freshness monitoring globally
    enabled: true

snapshots:
  dbt_anomaly_detection:
    +target_schema: "{{ 'dbt_anomaly_detection' if not target.name.startswith('dev_') else target.schema }}"
    +tags: ["anomaly_detection", "snapshot"]

models:
  dbt_anomaly_detection:
    +materialized: incremental
    +on_schema_change: "append_new_columns"
    +schema: "{{ 'dbt_anomaly_detection' if not target.name.startswith('dev_') else target.schema }}"
    # In dev: uses dev_<username> schema
    # In prod: uses dbt_anomaly_detection schema
    volume:
      +tags: ["anomaly_detection", "volume"]
    freshness:
      +tags: ["anomaly_detection", "freshness"]
    testing:
      # Development/example models - disabled by default for published package
      +enabled: false
      +tags: ["anomaly_detection", "testing", "examples"]

tests:
  dbt_anomaly_detection:
    +store_failures: true
